### ISSUE TITLE
What do you think of Node.js?

### ISSUE THREAD

**Issue by sindresorhus** [honglio/ama#1]

**Comment by honglio** [comment]
Using Node.js more than 2 years, and now a Node.js fans. I would like to compare it with other web tech in this answer.

The first is performance, which is not as good as imagined. System memory usage is as the same grade as  Ruby, more than PHP, Python. IO proformance is better than PHP, because of good control of the asynchronous process. Personally feel that the performance of Node.js has a great potential, because there are many large projects in the effort to improve the performance of JavaScript virtual machine, such as many modern browsers; at the same time, JavaScript is a simple language, also an open standard, which is unlike Python and PHP that taking compatibility into account and is difficult to improve the performance.

Then is the package and library management. NPM is a very good use of package manager. JavaScript has a short learning curve, and JavaScript has a lot of good front-end library was ported to the back-end. As the result, the package in NPM is now more than PyPI and RubyGems, and far more than Composer. In the development of Node.js project, different with PHP, we are not afraid to add 3rd part library dependency. Every time when you need to look for a library to achieve a certain goal, just search existing NPM package, and often can be found. So the development of Node.js project is basically a combination of librarys, even though a very small independent needs, which is more like UNIX. On the other hand, the Node.js community is very open source friendly, where the most of the libraries are on Github, and in the use of a very loose agreement, such as MIT, unlike GPL which is "aggressive".

Tool chain. Node.js has a lot of good tool chain, such as [grunt](http://www.gruntjs.net), [less](http://lesscss.org), yo(written by you), [mocha](github.com/mochajs/mocha), [phantom](http://phantomjs.org/), and so on. It's far better than PHP.

Grammar. I want to emphasize that the syntax of JavaScript is simple and flexible, thanks to JSON, which is the most common data format in the field of Web, and JavaScript has a native support for it! In JavaScript, all the data structures are almost a inheritance of JSON -- object, arrays, functions, classes and objects. Of course, it also has down side.  Because of historical problems, JavaScript's syntax is not that beautiful, but we have a variety of pre compiled tools, such as CoffeeScript, TypeScript, Dart, LiveScript and ClojureScript. There is always one good fit for you.

Finally, learning curve of Node.js. In my opinion, to learn Node.js, the first step is to understand Node.js asynchronous IO and callback process, which is the most different between Node.js and other mainstream programming language. And the second step is to look at top 100 librarys in NPM, just to know what each library does. After these two step, congratulations, you are a Node.js developer.

**Comment by sindresorhus** [comment]
:+1: Good answer ;)

## 

_Btw, you close the issue when answered._
