### ISSUE TITLE
what's you daily schedule?

### ISSUE THREAD

**Issue by Jayin** [honglio/ama#4]

**Comment by honglio** [comment]
As Web Developer, my typical day is like this:

08:45 - sit at my chair, turn my monitors on and make a little pray; 09:15 - check my emails;09:30 - define my daily goals: need to fix this, finish that, etc;09:35 - start coding;11:00 - little pause to drink water and breathe some air;11:05 - back to code;12:30 - lunch;13:15 - check my emails;13:20 - take some time to read news/Quora/SO;13:40 - back to code;16:30 - little pause to eat some fruit, drink water and breathe some air;16:40 - back to code;18:10 - finish work - check what I did and what I couldn't.18:15 - check my emails;18:30 - thank God to another good day of work and drive home;

Sometimes I had no time to quora/so, because replying emails can take too much time. But I try to take at least 5 min to read some news.

Other days I can't take 45min to lunch, often because of some deadline or other urgent problem, so I eat some fruit/juice within 15 min, and back to code again.

In general, is not a stressful day, because I just love what I do.

PS: Coding =  thinking, researching, interacting with other programmers, white board prototyping... and finally.... typing (wearing headphones).
